# ─────────────────────────────────────────────────────────────────
# Daftar nama assignee yang dijadikan acuan perbandingan
# Tambah / hapus nama langsung di sini
# ─────────────────────────────────────────────────────────────────

LIST_TEAMS = [
    'Affinia Maghrysa',
    'Azhar',
    'Kevin Hardianus Salim',
    'Rasya Bhisma Raharjo',
    'Izzat Inayaturrahman Haryono',
    'Martiza Aurelia Ahmad',
    'Rein Hard Alexander Kupa',
    'Yoga Firza Sabbihisma',
    'Revania Priscilla Lalenoh',
    'Cintiya Dita Dwi Fitriani',
    'Mastuari Octafina Sirumapea',
    'Muhammad Fahmy Aziz',
    'Steven Hanjaya',
    'Ajaya Saputra',
    'Ivander Albert Liestyo',
    'Sheilla Anjani',
    'Vanessa Verensia',
    'Alfiyanto Kondolele',
    'Violita Reviana Wijaya',
    'Listya Wulandari Mardiah',
    'Wilsen Wijaya',
    'Nilam Cahya',
    'Raihan Bilal Bagaswara',
    'Syifa Khairunnisa',
    'Yesha Ayutara Gunawan',
    'Natanael David Wibowo',
    'Parhan Hambali',
    'Erick Jonathan',
    'Adinda Rahmi',
    'Adytia Pati Rangga',
    'Evie Sintia S',
    'Vilda Mega Dwifanka Loomeyer',
    'Jansen Jonatan',
    'Dimas Athaya Purwoko',
    'Muhammad Rifqi Fauzi Ramdhani',
    'Jose Marco Adriano',
    'Bagus Arief Setyanto',
    'Imas Masriyah',
    'Nicholas Christopher',
    'Marcellino Haensch Cezio Kurniawan',
    'Kevien Er Aldo Ukla Basti',
    'Siti Mariam',
    'Mourenho Vireal',
    'Bunardi Budiman',
    'Putri Rana Khairina',
    'Tri Seltawika',
    'Muhammad Rayyan Faadhil Heraspati',
    'Joshua Azarya',
    'Nayaka Parikesit Bhamakerti',
    'Jeremy Christiano Elvan Hega',
    'Dea Sefiana',
    'Antony Willson',
    'Raven Derrick Bee',
    'Dipika Syaiban Ainun',
    'Aditama Nugraha',
    'Raymond Gandi Saor Simamora',
    'Dede Chandra Kirana',
    'Michael Agustinus Santoso',
    'Raymond Kent',
    'Eri Hadianto'
]